# Generated by Django 5.2.1 on 2025-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_observed', models.DateTimeField(help_text='When the observation was made (date & time).')),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='observations/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was first created.')),
            ],
        ),
    ]
