# Generated by Django 6.0.3 on 2026-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_observation_prediction_confidence_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-date_observed']},
        ),
        migrations.AddField(
            model_name='observation',
            name='ai_identified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observation',
            name='category',
            field=models.CharField(choices=[('bird', 'Bird'), ('mammal', 'Mammal'), ('reptile', 'Reptile'), ('insect', 'Insect'), ('plant', 'Plant'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='observations/'),
        ),
    ]
