"""
BioScout RAG Knowledge Base — 50 species documents for Pakistan and South Asia.
Each document contains structured fields used for both BM25 and vector search.
"""
from typing import Any


def get_all_documents() -> list[dict[str, Any]]:
    """Return the full list of 50 species knowledge documents."""
    return SPECIES_DOCUMENTS


SPECIES_DOCUMENTS: list[dict[str, Any]] = [
    # ── BIRDS (15) ────────────────────────────────────────────────────────────
    {
        "species_name": "House Sparrow",
        "scientific_name": "Passer domesticus",
        "category": "bird",
        "habitat": "Urban areas, farmland, gardens, roadsides",
        "diet": "Seeds, grains, insects, scraps",
        "predators": "Cats, hawks, falcons",
        "prey": "Insects, seeds",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Europe, Asia, Africa, introduced worldwide",
        "physical_description": "Small brown bird, 14-16cm. Males have grey crown, black bib, chestnut back. Females are plain brown with buff eye-stripe.",
        "behavior": "Highly social, forms large flocks. Nests in building crevices, roof tiles, and dense shrubs. Dust-bathes regularly.",
        "reproduction": "3-5 eggs per clutch, 2-3 broods per year. Both parents incubate for 11-14 days.",
        "fun_facts": "One of the most studied birds in the world. Population has declined 60% in UK since 1970s due to urban changes.",
        "threats": "Urbanisation, loss of nesting sites, pesticide use reducing insect food supply",
        "description": "House Sparrow is one of the most familiar birds in Pakistan, found in every city, town, and village. It thrives alongside humans and has followed human settlement across the globe. In Lahore and Karachi, flocks of sparrows are a constant presence in markets, parks, and residential areas. Despite being Least Concern globally, urban sparrow populations have declined sharply in many cities due to modern building designs that eliminate nesting cavities and pesticide use that reduces insect availability for chicks.",
    },
    {
        "species_name": "Common Myna",
        "scientific_name": "Acridotheres tristis",
        "category": "bird",
        "habitat": "Urban areas, open woodland, farmland, roadsides",
        "diet": "Omnivore — insects, fruit, scraps, small vertebrates",
        "predators": "Raptors, cats",
        "prey": "Insects, lizards, small frogs",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South Asia, Southeast Asia, introduced to Australia, Africa, Middle East",
        "physical_description": "Brown body, black head, yellow bill and eye patch, white wing patches visible in flight. 23-26cm.",
        "behavior": "Bold and aggressive. Displaces native cavity-nesting birds. Roosts communally in thousands. Excellent mimic.",
        "reproduction": "4-6 eggs, incubation 13-14 days. Nests in tree holes, building gaps.",
        "fun_facts": "Listed as one of the world's 100 worst invasive species by IUCN. Can mimic human speech.",
        "threats": "Considered invasive outside native range; competes with native species for nest sites",
        "description": "Common Myna is one of the most successful birds in the world, thriving in human-modified landscapes across Pakistan. Its intelligence, adaptability, and aggressive territorial behaviour have made it dominant in urban ecosystems. In Karachi and Lahore, mynas are ubiquitous — raiding fruit stalls, nesting in air conditioner units, and mobbing larger birds. While native to South Asia, its introduction to other continents has caused significant ecological damage by outcompeting native hole-nesting birds.",
    },
    {
        "species_name": "Hoopoe",
        "scientific_name": "Upupa epops",
        "category": "bird",
        "habitat": "Open woodland, orchards, gardens, farmland",
        "diet": "Insects, larvae, small reptiles, earthworms",
        "predators": "Raptors, cats, snakes",
        "prey": "Beetles, ants, grasshoppers, mole crickets",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Europe, Asia, Africa",
        "physical_description": "Unmistakable pinkish-brown bird with black-and-white barred wings, long curved bill, and erectile fan-shaped crest. 25-32cm.",
        "behavior": "Probes soil with long bill for insects. Raises crest when alarmed. Solitary outside breeding season.",
        "reproduction": "5-8 eggs in tree holes or wall crevices. Female incubates alone for 15-18 days.",
        "fun_facts": "National bird of Israel. Mentioned in the Quran. Produces foul-smelling secretion from preen gland to deter predators.",
        "threats": "Pesticide use reducing insect prey, habitat loss",
        "description": "The Hoopoe is one of Pakistan's most distinctive and beautiful birds, instantly recognisable by its spectacular crest and boldly patterned wings. It is a common resident in Peshawar's gardens, orchards, and the agricultural areas of Punjab and Sindh. The Hoopoe feeds by probing the ground with its long curved bill, extracting beetle larvae and earthworms. It is a bird of cultural significance across the Islamic world, mentioned in the Quran as the messenger of Prophet Sulaiman (Solomon).",
    },
    {
        "species_name": "Common Peafowl",
        "scientific_name": "Pavo cristatus",
        "category": "bird",
        "habitat": "Dry deciduous forest, scrubland, near water",
        "diet": "Seeds, insects, small reptiles, berries",
        "predators": "Leopards, dholes, jackals",
        "prey": "Snakes, lizards, insects",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent including Pakistan, introduced worldwide",
        "physical_description": "Male has iridescent blue-green plumage and elaborate 'train' of up to 200 elongated tail feathers with eye-spots. Female (peahen) is brown. Up to 2.3m including train.",
        "behavior": "Males display train in fan shape to attract females. Roosts in trees. Loud calls at dawn and dusk.",
        "reproduction": "4-8 eggs, incubation 28 days. Female raises chicks alone.",
        "fun_facts": "The 'eyes' on the tail feathers are called ocelli. Can fly despite their size. Sacred in many South Asian traditions.",
        "threats": "Habitat loss, hunting for feathers and meat",
        "description": "Common Peafowl (also called Peacock) is found in the forests and scrublands of Sindh and parts of Punjab in Pakistan. The male's spectacular iridescent plumage and elaborate courtship display make it one of the most visually stunning birds in the world. In Pakistan, peafowl are found near water sources in dry forest areas and are sometimes kept semi-wild around shrines and parks. They play an ecological role as seed dispersers and as predators of snakes and insects.",
    },
    {
        "species_name": "Houbara Bustard",
        "scientific_name": "Chlamydotis macqueenii",
        "category": "bird",
        "habitat": "Desert, semi-desert, arid steppe, sandy plains of Balochistan and Sindh",
        "diet": "Insects, lizards, seeds, plant matter",
        "predators": "Falcons, eagles, foxes",
        "prey": "Insects, lizards, small rodents",
        "conservation_status": "VU",
        "found_in_pakistan": True,
        "geographical_range": "Central Asia, Middle East, Pakistan — winters in Balochistan and Sindh",
        "physical_description": "Large ground bird, 55-65cm. Sandy-brown plumage with black and white neck markings. Long neck, long legs. Cryptic desert camouflage.",
        "behavior": "Runs rather than flies when threatened. Males perform elaborate spinning courtship display. Migratory — winters in Pakistan.",
        "reproduction": "2-4 eggs laid on bare ground. Female incubates alone for 23 days.",
        "fun_facts": "Iconic desert bird of Balochistan. Traditionally hunted by Arab falconers — a major diplomatic and conservation issue. Pakistan hosts critical wintering populations.",
        "threats": "Illegal falconry hunting by Gulf royalty, habitat degradation, overgrazing, climate change",
        "description": "Houbara Bustard is one of Pakistan's most iconic desert birds and a Vulnerable species that winters in the arid plains of Balochistan and Sindh. It is the traditional quarry of Arab falconers, and illegal hunting by visiting dignitaries has been a major conservation controversy in Pakistan for decades. Pakistan hosts some of the most important wintering populations of this species in the world. The Houbara is a master of desert camouflage, blending perfectly into sandy terrain. Conservation breeding programmes have been established to supplement wild populations.",
    },
    {
        "species_name": "Black Kite",
        "scientific_name": "Milvus migrans",
        "category": "bird",
        "habitat": "Urban areas, open country, near water, rubbish dumps",
        "diet": "Carrion, fish, small mammals, scraps, insects",
        "predators": "Larger eagles",
        "prey": "Fish, rodents, carrion, garbage",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Europe, Asia, Africa, Australia",
        "physical_description": "Medium-sized brown raptor with forked tail. 55-65cm wingspan 140-155cm. Pale head, yellow bill.",
        "behavior": "Highly aerial, soars on thermals for hours. Gregarious, roosts communally. Bold scavenger in cities.",
        "reproduction": "2-3 eggs, incubation 31-38 days. Both parents incubate.",
        "fun_facts": "One of the most abundant raptors in the world. Known to steal food from people's hands in cities.",
        "threats": "Poisoning from eating poisoned carcasses, electrocution on power lines",
        "description": "Black Kite is the most common raptor in Pakistani cities, with thousands soaring over Lahore, Karachi, and Islamabad on any given day. It is an opportunistic scavenger that plays a vital sanitation role in urban ecosystems, consuming carrion, fish scraps, and garbage. Despite its abundance, the Black Kite is an impressive flier, capable of sustained soaring and precise aerial manoeuvres. It is a year-round resident in Pakistan with additional winter migrants arriving from Central Asia.",
    },
    {
        "species_name": "Rose-ringed Parakeet",
        "scientific_name": "Psittacula krameri",
        "category": "bird",
        "habitat": "Woodland, urban parks, gardens, farmland",
        "diet": "Fruits, seeds, flowers, buds, nectar",
        "predators": "Raptors, cats",
        "prey": "None — herbivore",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Sub-Saharan Africa, South Asia; introduced to Europe, Middle East",
        "physical_description": "Bright green, 38-42cm including long tail. Males have pink and black neck ring. Loud screeching call.",
        "behavior": "Highly social, forms large noisy flocks. Roosts communally. Nests in tree holes.",
        "reproduction": "3-6 eggs, incubation 22-24 days.",
        "fun_facts": "Has established feral populations in over 35 countries. Can live 25-30 years.",
        "threats": "Crop damage leads to persecution; invasive in Europe",
        "description": "Rose-ringed Parakeet is one of the most familiar birds in Pakistani cities, forming large, noisy flocks that roost in urban trees. In Islamabad, flocks of hundreds can be seen flying at dusk to communal roost sites. The species is highly adaptable and has successfully colonised cities across Europe and the Middle East after escaping from captivity. In Pakistan, it is a native species and an important seed disperser, though it can cause significant damage to fruit crops.",
    },
    {
        "species_name": "Barn Owl",
        "scientific_name": "Tyto alba",
        "category": "bird",
        "habitat": "Open farmland, grassland, barns, old buildings",
        "diet": "Small mammals, especially rodents",
        "predators": "Eagle owls, large hawks",
        "prey": "Mice, rats, voles, shrews",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Almost worldwide except polar regions and some islands",
        "physical_description": "Heart-shaped white face, pale golden-buff upperparts, white underparts. 33-39cm. Silent flight.",
        "behavior": "Strictly nocturnal. Hunts by sound — can locate prey in complete darkness. Roosts in dark buildings.",
        "reproduction": "4-7 eggs, incubation 29-34 days. Can breed twice a year if food is abundant.",
        "fun_facts": "Can eat its own body weight in rodents per night. Pellets contain undigested bones and fur.",
        "threats": "Rodenticide poisoning (secondary), barn conversions removing nest sites, road traffic",
        "description": "Barn Owl is a widespread but often unseen resident of Pakistan's agricultural areas. Its ghostly white appearance and silent flight have given rise to many local superstitions. Ecologically, it is one of the most valuable birds for farmers — a single pair can consume over 1,000 rodents per year, providing free pest control. In Pakistan, Barn Owls nest in old mosques, abandoned buildings, and large trees. They are threatened by the widespread use of rodenticides which poison them through their prey.",
    },
    {
        "species_name": "Common Kingfisher",
        "scientific_name": "Alcedo atthis",
        "category": "bird",
        "habitat": "Rivers, streams, lakes, ponds with clear water",
        "diet": "Small fish, aquatic insects, crustaceans",
        "predators": "Cats, sparrowhawks, rats",
        "prey": "Fish, aquatic invertebrates",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Europe, Asia, North Africa",
        "physical_description": "Brilliant electric-blue upperparts, orange underparts, long dagger-like bill. 17-19cm. Unmistakable.",
        "behavior": "Perches motionless over water, dives headfirst to catch fish. Highly territorial. Fast direct flight.",
        "reproduction": "6-7 eggs in burrow dug into riverbank. Both parents incubate for 19-21 days.",
        "fun_facts": "Can see underwater due to special eye adaptation. Dives at up to 40 km/h.",
        "threats": "Water pollution, river bank disturbance, drought",
        "description": "Common Kingfisher is one of Pakistan's most jewel-like birds, a flash of electric blue and orange along rivers and lakes. It is found at Rawal Lake in Islamabad, along the Ravi and Chenab rivers, and at wetlands throughout the country. The Kingfisher is an indicator species — its presence signals clean, fish-rich water. Declining water quality and river bank disturbance have reduced populations in many areas. It hunts by plunge-diving from a perch, catching small fish with pinpoint accuracy.",
    },
    {
        "species_name": "White Wagtail",
        "scientific_name": "Motacilla alba",
        "category": "bird",
        "habitat": "Open areas near water, urban areas, farmland",
        "diet": "Insects, small invertebrates",
        "predators": "Cats, sparrowhawks",
        "prey": "Flies, beetles, worms",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Europe, Asia, Africa",
        "physical_description": "Black and white bird with long wagging tail. 16-19cm. Distinctive bobbing walk.",
        "behavior": "Constantly wags tail up and down. Runs rapidly after insects. Roosts communally in winter.",
        "reproduction": "5-6 eggs, incubation 12-14 days.",
        "fun_facts": "The tail wagging behaviour is thought to flush insects from grass. Winter roosts can contain thousands of birds.",
        "threats": "Pesticide use reducing insect prey",
        "description": "White Wagtail is a common winter visitor and resident in Pakistan, found near water bodies, on lawns, and in urban areas across the country. Its characteristic tail-bobbing walk makes it instantly recognisable. In Pakistan, large winter roosts form in city trees, sometimes containing thousands of birds. It is one of the most widespread birds in the world, with multiple subspecies breeding from Iceland to Japan.",
    },
    {
        "species_name": "Red Junglefowl",
        "scientific_name": "Gallus gallus",
        "category": "bird",
        "habitat": "Tropical and subtropical forest edges, scrub",
        "diet": "Seeds, insects, berries, small reptiles",
        "predators": "Foxes, mongooses, raptors, snakes",
        "prey": "Insects, seeds",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Male has brilliant red, orange, and gold plumage with red comb and wattles. Female is brown and cryptic. 43-78cm.",
        "behavior": "Scratches ground for food. Males crow at dawn. Roosts in trees at night.",
        "reproduction": "5-12 eggs, incubation 21 days. Female incubates alone.",
        "fun_facts": "Ancestor of all domestic chickens. Domesticated approximately 8,000 years ago in Southeast Asia.",
        "threats": "Hybridisation with domestic chickens threatening genetic purity of wild populations",
        "description": "Red Junglefowl is the wild ancestor of the domestic chicken and is found in the forested foothills of KPK and Azad Kashmir in Pakistan. It inhabits forest edges and dense scrub, foraging on the ground for seeds and insects. The male's brilliant plumage and loud crowing are unmistakable in its forest habitat. Wild populations face threats from hybridisation with free-ranging domestic chickens, which dilutes the genetic integrity of the wild species.",
    },
    {
        "species_name": "Sarus Crane",
        "scientific_name": "Antigone antigone",
        "category": "bird",
        "habitat": "Wetlands, flooded fields, marshes, rivers",
        "diet": "Roots, tubers, insects, fish, frogs",
        "predators": "Tigers, leopards (eggs/chicks)",
        "prey": "Fish, frogs, insects, plant matter",
        "conservation_status": "VU",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent, Southeast Asia, Australia",
        "physical_description": "World's tallest flying bird at up to 1.8m. Grey body, red head and upper neck, white crown. Wingspan up to 2.4m.",
        "behavior": "Mates for life. Elaborate dancing courtship display. Highly vocal with trumpeting calls.",
        "reproduction": "2 eggs, incubation 31-35 days. Both parents raise chicks.",
        "fun_facts": "World's tallest flying bird. Pairs mate for life and are symbols of fidelity in South Asian culture.",
        "threats": "Wetland drainage, pesticide use, hunting, egg collection",
        "description": "Sarus Crane is the world's tallest flying bird and a Vulnerable species found in the wetlands of Sindh and Punjab in Pakistan. It is revered in South Asian culture as a symbol of lifelong fidelity, as pairs mate for life and perform elaborate dancing displays. Pakistan's Sarus Crane population has declined dramatically due to wetland drainage, pesticide contamination of food, and disturbance at nesting sites. Conservation efforts focus on protecting key wetland habitats.",
    },
    {
        "species_name": "Painted Stork",
        "scientific_name": "Mycteria leucocephala",
        "category": "bird",
        "habitat": "Wetlands, shallow lakes, flooded fields, rivers",
        "diet": "Fish, frogs, crustaceans, insects",
        "predators": "Eagles, crocodiles",
        "prey": "Fish, frogs, aquatic invertebrates",
        "conservation_status": "NT",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Large white bird with pink tertial feathers, yellow bill, bare orange-red face. 93-102cm. Wingspan 150-160cm.",
        "behavior": "Feeds by wading and sweeping bill through water. Nests colonially in trees near water.",
        "reproduction": "3-5 eggs, incubation 28-32 days. Colonial nester.",
        "fun_facts": "Uses tactile hunting — sweeps bill through water and snaps shut when it touches prey.",
        "threats": "Wetland loss, water pollution, disturbance at nesting colonies",
        "description": "Painted Stork is a Near Threatened wading bird found at major wetlands in Pakistan, particularly in Sindh. Its striking pink and white plumage and bare orange face make it one of the most beautiful waterbirds in South Asia. It feeds by wading through shallow water and using its sensitive bill to detect fish by touch. Painted Storks nest in large colonies in trees near water, often alongside other waterbirds. Wetland drainage and water pollution are the primary threats to this species in Pakistan.",
    },
    {
        "species_name": "Asian Pied Starling",
        "scientific_name": "Gracupica contra",
        "category": "bird",
        "habitat": "Open woodland, farmland, urban areas, near water",
        "diet": "Insects, fruit, nectar, scraps",
        "predators": "Raptors, cats",
        "prey": "Insects, earthworms",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Black and white bird with orange-red bill and eye patch. 23-25cm.",
        "behavior": "Social, often in small flocks. Forages on ground and in trees. Loud varied calls.",
        "reproduction": "4-6 eggs in domed nest in tree or bush.",
        "fun_facts": "Often associates with cattle, feeding on insects disturbed by their movement.",
        "threats": "Habitat loss, trapping for cage bird trade",
        "description": "Asian Pied Starling is a common and conspicuous bird in Pakistan's lowland areas, particularly in Sindh and Punjab. Its bold black and white plumage and bright orange bill make it easy to identify. It is a highly adaptable species found in farmland, urban parks, and near water. Like many starlings, it is an important insect predator and seed disperser. It is frequently trapped for the cage bird trade, which has reduced populations in some areas.",
    },
    {
        "species_name": "Alexandrine Parakeet",
        "scientific_name": "Psittacula eupatria",
        "category": "bird",
        "habitat": "Forest, woodland, mangroves, farmland",
        "diet": "Fruits, seeds, flowers, buds, bark",
        "predators": "Raptors, snakes",
        "prey": "None — herbivore",
        "conservation_status": "NT",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Large green parakeet, 56-62cm including long tail. Males have pink and black neck ring and red shoulder patch.",
        "behavior": "Loud screeching calls. Roosts communally. Nests in tree holes.",
        "reproduction": "2-4 eggs, incubation 24-28 days.",
        "fun_facts": "Named after Alexander the Great who brought them to Europe. One of the largest parakeets in the world.",
        "threats": "Trapping for pet trade, habitat loss, crop raiding leads to persecution",
        "description": "Alexandrine Parakeet is a Near Threatened species found in the forests and woodland of Pakistan, particularly in KPK and Punjab. It is the largest parakeet in South Asia and one of the most heavily trapped birds for the international pet trade. Named after Alexander the Great, who reportedly brought specimens back to Europe after his Indian campaign, it has been kept as a pet for over 2,000 years. Wild populations have declined significantly due to trapping and habitat loss.",
    },
    {
        "species_name": "Oriental Turtle Dove",
        "scientific_name": "Streptopelia orientalis",
        "category": "bird",
        "habitat": "Forest, woodland, scrub, farmland",
        "diet": "Seeds, grain, berries, insects",
        "predators": "Raptors, cats, foxes",
        "prey": "Seeds, grain",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Asia from Siberia to Japan, south to India",
        "physical_description": "Medium dove, 30-35cm. Scaly brown-orange back, blue-grey head, black and white neck patch.",
        "behavior": "Solitary or in pairs. Soft purring call. Migratory in northern parts of range.",
        "reproduction": "2 eggs, incubation 15-16 days.",
        "fun_facts": "One of the most hunted birds in the Mediterranean during migration.",
        "threats": "Hunting during migration, habitat loss",
        "description": "Oriental Turtle Dove is a common resident and winter visitor in Pakistan, found in forests, woodland edges, and farmland across the country. Its soft purring call is a familiar sound in rural Pakistan. It feeds primarily on seeds and grain, often foraging on the ground in agricultural areas. The species is a popular game bird and is heavily hunted during migration in some parts of its range, though populations remain stable in Pakistan.",
    },
    # ── MAMMALS (10) ─────────────────────────────────────────────────────────
    {
        "species_name": "Snow Leopard",
        "scientific_name": "Panthera uncia",
        "category": "mammal",
        "habitat": "Alpine and subalpine zones, rocky terrain, 3000-5500m elevation",
        "diet": "Blue sheep (bharal), ibex, marmots, hares",
        "predators": "Humans (poaching)",
        "prey": "Blue sheep, Himalayan ibex, marmots, deer",
        "conservation_status": "VU",
        "found_in_pakistan": True,
        "geographical_range": "Central Asia mountain ranges — Himalayas, Karakoram, Hindu Kush, Tian Shan",
        "physical_description": "Large cat, 75-130cm body length. Pale grey with black rosettes, long thick tail (nearly body length), large paws for snow walking.",
        "behavior": "Solitary and crepuscular. Uses tail for balance on rocky terrain. Covers vast home ranges of 30-65 sq km.",
        "reproduction": "2-3 cubs, born May-June. Cubs stay with mother 18-22 months.",
        "fun_facts": "Cannot roar — makes a non-threatening puffing sound called a 'chuff'. Tail is so long it can be used as a scarf.",
        "threats": "Poaching for fur and bones, retaliatory killing by herders, prey depletion, climate change",
        "description": "Snow Leopard is Pakistan's most iconic and elusive large predator — a rare, endangered mountain predator found in the Karakoram, Himalayan, and Hindu Kush mountain ranges of Gilgit-Baltistan and KPK. This high altitude Pakistan mammal is classified as Vulnerable (VU) by IUCN, making it a critically threatened species. Pakistan is estimated to hold 200-420 individuals, making it one of the most important countries for snow leopard conservation. As an endangered rare mammal of Pakistan's Northern Areas and Gilgit-Baltistan, it is threatened by poaching for its beautiful fur and bones used in traditional medicine, retaliatory killing by herders whose livestock it occasionally takes, and climate change shrinking its alpine habitat. Conservation programmes involving local communities as wildlife guardians have shown promising results in reducing conflict.",
    },
    {
        "species_name": "Rhesus Macaque",
        "scientific_name": "Macaca mulatta",
        "category": "mammal",
        "habitat": "Forest, scrubland, urban areas, near temples and shrines",
        "diet": "Omnivore — fruits, seeds, insects, small animals, human food",
        "predators": "Leopards, dholes, large raptors",
        "prey": "Insects, small vertebrates, eggs",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South, Central, and Southeast Asia",
        "physical_description": "Medium-sized monkey, 47-64cm. Brown-grey fur, pink face, short tail. Males larger than females.",
        "behavior": "Highly social, lives in troops of 20-200. Complex social hierarchy. Excellent swimmer.",
        "reproduction": "Single infant, gestation 164 days. Infant clings to mother.",
        "fun_facts": "Most widely used primate in medical research. First primate to be cloned. Sent to space before humans.",
        "threats": "Habitat loss, conflict with humans, trapping for research",
        "description": "Rhesus Macaque is the most common primate in Pakistan, found in the Margalla Hills near Islamabad, the Murree hills, and forested areas of KPK and AJK. Troops of macaques are a familiar sight along roadsides and near tourist areas, where they have become habituated to humans and dependent on handouts. This dependency on human food is ecologically problematic, disrupting their natural foraging behaviour and creating conflict. The species is the most widely used primate in biomedical research and has contributed enormously to human medicine.",
    },
    {
        "species_name": "Desert Fox",
        "scientific_name": "Vulpes vulpes pusilla",
        "category": "mammal",
        "habitat": "Desert, semi-arid scrubland, open grassland, sandy plains",
        "diet": "Rodents, insects, birds, eggs, fruit, carrion",
        "predators": "Wolves, jackals, large raptors",
        "prey": "Rodents, insects, small birds",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Pakistan, India, Afghanistan — arid zones of South Asia",
        "physical_description": "Small fox, 45-60cm body. Sandy-pale fur, bushy tail with white tip, large ears for heat dissipation. 1.5-3kg.",
        "behavior": "Monogamous pairs share burrow system. Nocturnal and crepuscular. Hunts alone.",
        "reproduction": "3-6 pups per litter, born January-March. Both parents raise pups.",
        "fun_facts": "Large ears help dissipate heat in desert environments. Highly adapted to arid conditions — can survive without drinking water.",
        "threats": "Habitat loss to agriculture, road kills, hunting for fur and body parts used in folk medicine",
        "description": "Desert Fox is a small, elegant canid found in the arid and semi-arid zones of Pakistan, particularly in Balochistan, Sindh, and southern Punjab. It is highly adapted to desert life, with large ears that help dissipate heat and the ability to survive without drinking water by obtaining moisture from prey. The Desert Fox is an important predator of rodents and insects, playing a key role in controlling agricultural pests. It is threatened by the conversion of desert habitat to farmland and road kills.",
    },
    {
        "species_name": "Himalayan Brown Bear",
        "scientific_name": "Ursus arctos isabellinus",
        "category": "mammal",
        "habitat": "Alpine meadows, subalpine forest, rocky slopes, 2000-5000m",
        "diet": "Omnivore — berries, roots, insects, fish, small mammals, carrion",
        "predators": "Humans (only significant predator)",
        "prey": "Marmots, pikas, fish, insects",
        "conservation_status": "CR",
        "found_in_pakistan": True,
        "geographical_range": "Himalayas, Karakoram, Hindu Kush, Central Asia",
        "physical_description": "Large bear, 150-200cm. Sandy-brown to reddish-brown fur. Distinctive shoulder hump. 100-250kg.",
        "behavior": "Solitary except mothers with cubs. Hibernates October-April. Excellent sense of smell.",
        "reproduction": "1-3 cubs born during hibernation in January-February. Cubs stay with mother 2-3 years.",
        "fun_facts": "Fewer than 150 remain in Pakistan. Can smell food from 20km away.",
        "threats": "Habitat loss, human-wildlife conflict, poaching for bile and body parts, climate change",
        "description": "Himalayan Brown Bear is a Critically Endangered subspecies found in the high mountain valleys of Swat, Chitral, and Gilgit-Baltistan in Pakistan. With fewer than 150 individuals remaining in the country, it is one of Pakistan's most endangered large mammals. It is threatened by habitat loss as forests are cleared for agriculture and firewood, human-wildlife conflict when bears raid crops and livestock, and poaching for bear bile used in traditional medicine. Conservation efforts focus on reducing conflict through better livestock protection and community education.",
    },
    {
        "species_name": "Himalayan Marmot",
        "scientific_name": "Marmota himalayana",
        "category": "mammal",
        "habitat": "Alpine meadows and grasslands, 3500-5200m elevation",
        "diet": "Grasses, herbs, roots, bulbs, insects",
        "predators": "Snow leopards, golden eagles, wolves, foxes",
        "prey": "None — herbivore/insectivore",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Himalayas, Karakoram, Tibetan Plateau",
        "physical_description": "Large ground squirrel, 47-67cm. Thick brown-grey fur, short legs, bushy tail. 4-8kg.",
        "behavior": "Colonial, lives in burrow systems. Hibernates 6-7 months. Loud alarm whistle when threatened.",
        "reproduction": "3-7 young per litter, born May-June after hibernation.",
        "fun_facts": "Key prey species for Snow Leopards. Can hibernate for up to 8 months. Alarm calls warn entire colony.",
        "threats": "Hunting for meat and fur, habitat degradation from overgrazing",
        "description": "Himalayan Marmot is a large, sociable ground squirrel found in the alpine meadows of Gilgit-Baltistan and KPK above 3,500m — a true high altitude Pakistan mammal of the Northern Areas and Karakoram mountains. It lives in colonies centred around complex burrow systems and hibernates for 6-7 months of the year. This hibernating mammal of Pakistan's alpine meadows is a critical prey species for Snow Leopards and Golden Eagles, forming a key link in the high-altitude food chain. Their loud alarm whistles alert the entire colony to approaching predators. They are hunted for their meat and fat, which is used in traditional medicine.",
    },
    {
        "species_name": "Pakistani Pangolin",
        "scientific_name": "Manis crassicaudata",
        "category": "mammal",
        "habitat": "Tropical and subtropical forest, grassland, scrubland of Pakistan",
        "diet": "Ants and termites exclusively",
        "predators": "Leopards, large pythons",
        "prey": "Ants, termites",
        "conservation_status": "EN",
        "found_in_pakistan": True,
        "geographical_range": "Pakistan, India — Indian subcontinent",
        "physical_description": "Covered in overlapping brown keratin scales. 45-75cm body, long tail. Rolls into ball when threatened. 10-16kg.",
        "behavior": "Nocturnal and solitary. Digs into ant and termite mounds with powerful claws. No teeth.",
        "reproduction": "Single offspring, carried on mother's tail.",
        "fun_facts": "Most trafficked mammal in the world. Scales are made of keratin — same as human fingernails. Can eat 70 million insects per year.",
        "threats": "Poaching for scales (used in traditional Chinese medicine) and meat — most trafficked mammal globally, critically endangered in Pakistan",
        "description": "Pakistani Pangolin is an Endangered species — a critically endangered rare mammal and one of the most threatened species in Pakistan — found in the forests and scrublands of Punjab, Sindh, and KPK. It is the most trafficked mammal in the world, with tens of thousands killed annually for their scales, which are used in traditional Chinese medicine despite having no proven medicinal value. The scales are made of keratin, the same material as human fingernails. Pangolins are critically important for ecosystem health, consuming up to 70 million ants and termites per year, controlling insect populations and aerating soil.",
    },
    {
        "species_name": "Indus River Dolphin",
        "scientific_name": "Platanista minor",
        "category": "mammal",
        "habitat": "Freshwater rivers — found ONLY in the Indus River system of Pakistan",
        "diet": "Fish, shrimp, catfish, freshwater invertebrates",
        "predators": "Humans (accidental bycatch, hunting)",
        "prey": "Fish, shrimp, freshwater invertebrates",
        "conservation_status": "EN",
        "found_in_pakistan": True,
        "geographical_range": "ENDEMIC to Pakistan — Indus River between Guddu and Sukkur barrages, Sindh",
        "physical_description": "Medium dolphin, 2-2.5m. Grey-brown, stocky body. Tiny eyes (functionally blind). Long beak with visible teeth. 70-110kg.",
        "behavior": "Swims on its side to navigate shallow water. Uses echolocation to hunt. Solitary or in small groups.",
        "reproduction": "Single calf, born after 9-10 months gestation. Calves nurse for 1 year.",
        "fun_facts": "Functionally blind — navigates entirely by echolocation. Found ONLY in Pakistan's Indus River. National symbol of Pakistan's freshwater biodiversity.",
        "threats": "Barrages fragmenting habitat, fishing net entanglement, water pollution, reduced river flow from irrigation",
        "description": "Indus River Dolphin is one of the world's rarest and most endangered freshwater dolphins, found exclusively in Pakistan's Indus River — making it a uniquely Pakistani species. It is Endangered with only around 1,800 individuals remaining, confined to a stretch of the Indus between Guddu and Sukkur barrages in Sindh. The dolphin is functionally blind, having evolved in the turbid Indus waters where vision is useless, and navigates entirely by echolocation. It is Pakistan's most iconic freshwater mammal and a flagship species for Indus River conservation. Major threats include barrages that fragment its habitat, accidental entanglement in fishing nets, and reduced river flow from irrigation.",
    },
    {
        "species_name": "Urial",
        "scientific_name": "Ovis vignei",
        "category": "mammal",
        "habitat": "Dry rocky hillsides, open grassland, semi-desert",
        "diet": "Grasses, herbs, shrubs",
        "predators": "Snow leopards, wolves, leopards",
        "prey": "None — herbivore",
        "conservation_status": "VU",
        "found_in_pakistan": True,
        "geographical_range": "Central Asia, Pakistan, India",
        "physical_description": "Medium wild sheep. Males have large curved horns and reddish-brown coat with white bib. 80-90cm at shoulder.",
        "behavior": "Lives in herds. Males fight for dominance during rut. Excellent climber on rocky terrain.",
        "reproduction": "1-2 lambs, born April-May.",
        "fun_facts": "One of the ancestors of domestic sheep. Males' horns can reach 100cm in length.",
        "threats": "Hunting (trophy and subsistence), competition with domestic livestock, habitat degradation",
        "description": "Urial is a Vulnerable wild sheep found on the rocky hillsides and grasslands of Balochistan, Punjab, and KPK in Pakistan. It is one of the most important trophy hunting species in Pakistan, with controlled hunting programmes generating revenue for local communities and conservation. However, uncontrolled poaching and competition with domestic livestock for grazing remain significant threats. The Urial is an important prey species for Snow Leopards and Wolves in mountain ecosystems.",
    },
    {
        "species_name": "Markhor",
        "scientific_name": "Capra falconeri",
        "category": "mammal",
        "habitat": "Steep rocky mountain terrain, scrub forest, 600-3600m",
        "diet": "Grasses, leaves, shrubs, herbs",
        "predators": "Snow leopards, wolves, leopards",
        "prey": "None — herbivore",
        "conservation_status": "NT",
        "found_in_pakistan": True,
        "geographical_range": "Pakistan, Afghanistan, India, Central Asia",
        "physical_description": "Large wild goat. Males have spectacular corkscrew horns up to 160cm. Shaggy coat, long beard. 65-115cm at shoulder.",
        "behavior": "Lives in small herds. Males solitary outside rut. Excellent climber.",
        "reproduction": "1-2 kids, born May-June.",
        "fun_facts": "National animal of Pakistan. Horns can grow up to 160cm. Name means 'snake eater' in Persian.",
        "threats": "Poaching for trophies and meat, habitat loss, competition with livestock",
        "description": "Markhor is Pakistan's national animal and one of the most magnificent wild goats in the world. Found in the rocky mountain terrain of Gilgit-Baltistan, KPK, and AJK, the male's spectacular corkscrew horns are among the most impressive in the animal kingdom. The species was once Endangered but has recovered to Near Threatened status thanks to community-based conservation programmes in Pakistan that allow controlled trophy hunting, with revenues shared with local communities who then protect the animals. It is a conservation success story.",
    },
    {
        "species_name": "Common Leopard",
        "scientific_name": "Panthera pardus",
        "category": "mammal",
        "habitat": "Forest, scrubland, rocky hills, near human settlements",
        "diet": "Deer, monkeys, dogs, livestock, rodents",
        "predators": "Tigers, lions (in Africa), humans",
        "prey": "Chital, monkeys, dogs, pigs, rodents",
        "conservation_status": "VU",
        "found_in_pakistan": True,
        "geographical_range": "Sub-Saharan Africa, South and Southeast Asia",
        "physical_description": "Large spotted cat, 90-165cm body. Yellow-gold coat with black rosettes. Melanistic (black) form exists. 17-90kg.",
        "behavior": "Solitary and nocturnal. Drags prey into trees to avoid scavengers. Excellent climber and swimmer.",
        "reproduction": "2-4 cubs, gestation 90-105 days. Cubs stay with mother 18-24 months.",
        "fun_facts": "Most widespread of all big cats. Can carry prey twice its own weight up a tree.",
        "threats": "Habitat loss, prey depletion, human-wildlife conflict, poaching for skin and bones",
        "description": "Common Leopard is found in the forested hills of KPK, AJK, and parts of Balochistan in Pakistan. It is the most adaptable of the big cats, able to survive in a wide range of habitats from dense forest to semi-arid scrubland. In Pakistan, leopards increasingly come into conflict with humans as forests are cleared and prey becomes scarce, leading to livestock predation and retaliatory killing. Conservation efforts focus on reducing conflict through better livestock protection and community awareness programmes.",
    },
    {
        "species_name": "Golden Jackal",
        "scientific_name": "Canis aureus",
        "category": "mammal",
        "habitat": "Open woodland, grassland, scrubland, urban fringes",
        "diet": "Omnivore — small mammals, birds, insects, fruit, carrion, garbage",
        "predators": "Wolves, leopards, large raptors",
        "prey": "Rodents, birds, insects, reptiles",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Southeast Europe, Middle East, South Asia, Southeast Asia",
        "physical_description": "Medium canid, 60-75cm body. Tawny-golden coat, bushy tail with black tip. 6-14kg.",
        "behavior": "Monogamous pairs with family groups. Nocturnal and crepuscular. Howls to communicate.",
        "reproduction": "3-8 pups per litter, born March-April.",
        "fun_facts": "Can hybridise with domestic dogs and wolves. Expanding range into Europe due to climate change.",
        "threats": "Persecution as livestock predator, habitat loss, road kills",
        "description": "Golden Jackal is a widespread and adaptable canid found throughout Pakistan's lowland areas, from the Indus plains to the foothills of the Himalayas. It is an important scavenger and predator of rodents, playing a key role in controlling pest populations and cleaning up carrion. Jackals are often persecuted as livestock predators, though they rarely take healthy adult animals. They are highly vocal, with pairs and family groups howling together at dusk — a characteristic sound of Pakistan's rural landscapes.",
    },
    # ── REPTILES (8) ─────────────────────────────────────────────────────────
    {
        "species_name": "Spectacled Cobra",
        "scientific_name": "Naja naja",
        "category": "reptile",
        "habitat": "Agricultural land, forest edges, near human settlements, scrubland",
        "diet": "Rodents, frogs, lizards, birds, eggs",
        "predators": "Mongooses, eagles, large raptors",
        "prey": "Rodents, frogs, lizards",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent including Pakistan",
        "physical_description": "Medium snake, 1.2-2.2m. Brown to black with distinctive spectacle hood marking on back of hood. Spreads hood when threatened.",
        "behavior": "Spreads hood and raises body when threatened. Primarily nocturnal. Excellent swimmer.",
        "reproduction": "10-30 eggs, female guards nest. Hatch after 48-69 days.",
        "fun_facts": "Named for the spectacle pattern on its hood. One of the 'Big Four' most dangerous venomous snakes in Pakistan. Venom is neurotoxic.",
        "threats": "Persecution by humans, habitat loss, collection for snake charming and medicine",
        "description": "Spectacled Cobra (also called Indian Cobra) is one of the most venomous and ecologically important snakes in Pakistan, found throughout the lowland areas of Sindh, Punjab, and KPK. It is named for the distinctive spectacle-shaped marking on the back of its hood. It is one of the 'Big Four' venomous snakes responsible for the majority of snakebite deaths in Pakistan. Despite its fearsome reputation, the cobra is an important predator of rodents, providing free pest control in agricultural areas. Its venom is neurotoxic and can be fatal without treatment.",
    },
    {
        "species_name": "Russell's Viper",
        "scientific_name": "Daboia russelii",
        "category": "reptile",
        "habitat": "Open grassland, scrubland, agricultural fields, forest edges",
        "diet": "Rodents, lizards, frogs, small birds",
        "predators": "Mongooses, large raptors, king cobras",
        "prey": "Rodents, lizards, frogs",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia — very common in Pakistan",
        "physical_description": "Heavy-bodied snake, 1.2-1.5m. Brown with three rows of dark brown oval spots outlined in black and white. Triangular head.",
        "behavior": "Slow-moving but aggressive when disturbed. Loud hissing warning. Primarily nocturnal.",
        "reproduction": "Viviparous — gives birth to 20-40 live young.",
        "fun_facts": "One of the 'Big Four' most dangerous snakes in Pakistan. Responsible for more snakebite deaths than any other snake in South Asia. Venom causes haemotoxic effects.",
        "threats": "Persecution by humans, habitat loss",
        "description": "Russell's Viper is one of the most dangerous and commonly encountered venomous snakes in Pakistan, found in open grasslands, agricultural fields, and scrubland across Sindh, Punjab, and KPK. It is responsible for more snakebite deaths than any other snake in South Asia, earning it a place in the 'Big Four' most dangerous snakes of Pakistan. Unlike cobras, Russell's Viper is slow-moving and well-camouflaged, making accidental encounters common in agricultural areas. Its haemotoxic venom causes severe internal bleeding and organ failure. Despite its danger, it plays a vital role in controlling rodent populations.",
    },
    {
        "species_name": "Monitor Lizard",
        "scientific_name": "Varanus bengalensis",
        "category": "reptile",
        "habitat": "Forest, scrubland, rocky terrain, near water",
        "diet": "Insects, eggs, small mammals, birds, carrion, fish",
        "predators": "Crocodiles, large raptors, pythons",
        "prey": "Insects, rodents, eggs, carrion",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Large lizard, up to 1.75m. Grey-brown with yellow spots. Long forked tongue, powerful claws.",
        "behavior": "Active during day. Excellent climber, swimmer, and runner. Uses tongue to smell.",
        "reproduction": "7-37 eggs laid in termite mounds or soil. No parental care.",
        "fun_facts": "Can run at 28 km/h. Forked tongue detects scent particles. Illegally hunted for skin used in leather goods.",
        "threats": "Hunting for skin, meat, and body parts used in traditional medicine; habitat loss",
        "description": "Bengal Monitor is the most common large lizard in Pakistan, found in forests, scrubland, and rocky terrain across the country. It is an important scavenger and predator, consuming carrion, insects, rodents, and eggs. Despite being protected under Pakistani law, it is heavily hunted for its skin, which is used in the leather goods industry, and for its body parts used in traditional medicine. Monitor lizards play a vital ecological role in controlling rodent and insect populations.",
    },
    {
        "species_name": "Star Tortoise",
        "scientific_name": "Geochelone elegans",
        "category": "reptile",
        "habitat": "Dry grassland, scrub forest, semi-arid areas",
        "diet": "Grasses, fallen fruit, flowers, cacti",
        "predators": "Jackals, mongooses, large raptors (juveniles)",
        "prey": "None — herbivore",
        "conservation_status": "VU",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent, Sri Lanka",
        "physical_description": "Medium tortoise, 15-38cm. Distinctive star-patterned shell with yellow radiating lines on black background.",
        "behavior": "Active during cooler parts of day. Aestivates during hottest months. Slow-moving.",
        "reproduction": "2-10 eggs per clutch, multiple clutches per year. Incubation 47-180 days.",
        "fun_facts": "One of the most trafficked reptiles in the world. Star pattern is unique to each individual.",
        "threats": "Illegal collection for pet trade, habitat loss, road kills",
        "description": "Indian Star Tortoise is a Vulnerable species found in the dry grasslands and scrub forests of Punjab and Sindh in Pakistan. Its beautiful star-patterned shell makes it one of the most sought-after reptiles in the illegal pet trade, with thousands collected annually for export to Asia and Europe. Each tortoise's star pattern is unique, like a fingerprint. In Pakistan, it is protected under wildlife laws but enforcement is weak. Habitat loss to agriculture and road kills are additional threats.",
    },
    {
        "species_name": "Marsh Crocodile",
        "scientific_name": "Crocodylus palustris",
        "category": "reptile",
        "habitat": "Rivers, lakes, marshes, reservoirs, coastal areas",
        "diet": "Fish, birds, mammals, carrion",
        "predators": "Humans (only significant predator of adults)",
        "prey": "Fish, waterfowl, mammals up to deer size",
        "conservation_status": "VU",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent, Iran",
        "physical_description": "Large crocodile, up to 4m. Grey-brown, broad snout. Distinguishable from gharial by broader snout.",
        "behavior": "Basks on riverbanks. Digs burrows during dry season. Ambush predator.",
        "reproduction": "25-30 eggs in mound nest. Female guards nest and assists hatchlings.",
        "fun_facts": "Sacred at Manghopir shrine near Karachi where over 100 crocodiles are fed by devotees.",
        "threats": "Habitat loss, hunting for skin and meat, human-wildlife conflict, water pollution",
        "description": "Marsh Crocodile is a Vulnerable species found in the rivers, lakes, and marshes of Sindh in Pakistan. It is the only crocodilian species in Pakistan and plays a vital role as an apex predator in freshwater ecosystems. The species has a unique cultural significance in Pakistan — at the Manghopir shrine near Karachi, over 100 crocodiles are considered sacred and fed by devotees. Despite this protection at some sites, the species is threatened by habitat loss, hunting, and water pollution across most of its range.",
    },
    {
        "species_name": "Saw-scaled Viper",
        "scientific_name": "Echis carinatus",
        "category": "reptile",
        "habitat": "Dry rocky areas, sandy desert, scrubland",
        "diet": "Lizards, frogs, small mammals, insects, scorpions",
        "predators": "Mongooses, large raptors",
        "prey": "Lizards, rodents, insects",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Middle East, South Asia, Africa",
        "physical_description": "Small viper, 30-90cm. Brown with pale oval markings. Distinctive saw-like scales on sides produce rasping sound.",
        "behavior": "Nocturnal. Produces warning sound by rubbing saw-like scales together. Sidewinding locomotion in sand.",
        "reproduction": "3-15 live young.",
        "fun_facts": "Responsible for more human deaths than any other snake species worldwide. Venom causes haemotoxic effects.",
        "threats": "Persecution by humans, habitat loss",
        "description": "Saw-scaled Viper is one of the most dangerous snakes in Pakistan and is responsible for more human deaths than any other snake species worldwide. It is found in the dry rocky areas and sandy deserts of Balochistan, Sindh, and Punjab. Despite its small size, it has a highly potent haemotoxic venom and an aggressive temperament. It produces a distinctive rasping warning sound by rubbing its saw-like scales together. It is a member of the 'Big Four' most medically important snakes in Pakistan.",
    },
    {
        "species_name": "Common Krait",
        "scientific_name": "Bungarus caeruleus",
        "category": "reptile",
        "habitat": "Agricultural land, scrubland, near human settlements, termite mounds",
        "diet": "Other snakes, lizards, frogs, small mammals",
        "predators": "Mongooses, large raptors",
        "prey": "Other snakes, lizards, frogs",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent",
        "physical_description": "Medium snake, 0.9-1.75m. Shiny black with white crossbands. Rounded body, small head.",
        "behavior": "Strictly nocturnal. Docile during day, aggressive at night. Enters homes seeking prey.",
        "reproduction": "6-15 eggs, female coils around eggs.",
        "fun_facts": "Venom is 15 times more potent than cobra venom. Bites often occur at night while people sleep.",
        "threats": "Persecution, habitat loss",
        "description": "Common Krait is one of the most venomous snakes in Pakistan and a member of the 'Big Four' responsible for most snakebite deaths. Its venom is highly neurotoxic — 15 times more potent than cobra venom — and bites are particularly dangerous because they are often painless, occurring at night while people sleep. The Krait is found throughout the lowland areas of Pakistan, entering homes at night in search of prey. Despite its danger to humans, it is an important predator of other snakes and rodents.",
    },
    {
        "species_name": "Chameleon",
        "scientific_name": "Chamaeleo zeylanicus",
        "category": "reptile",
        "habitat": "Dry scrubland, open woodland, gardens",
        "diet": "Insects, small lizards",
        "predators": "Snakes, raptors, mongooses",
        "prey": "Insects, small lizards",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent, Sri Lanka",
        "physical_description": "Medium lizard, 23-37cm. Laterally compressed body, prehensile tail, independently moving eyes, colour-changing skin.",
        "behavior": "Slow-moving arboreal lizard. Changes colour for camouflage and communication. Shoots tongue at prey.",
        "reproduction": "10-30 eggs buried in soil.",
        "fun_facts": "Eyes move independently — can look in two directions simultaneously. Tongue is longer than body.",
        "threats": "Collection for pet trade, habitat loss, pesticide use reducing insect prey",
        "description": "Indian Chameleon is found in the dry scrublands and open woodland of Sindh and southern Punjab in Pakistan. It is one of the most remarkable reptiles in the world, capable of changing colour for camouflage and communication, shooting its tongue at insects faster than the eye can follow, and moving its eyes independently to look in two directions simultaneously. It is collected for the pet trade and threatened by habitat loss and pesticide use that reduces its insect prey.",
    },
    # ── PLANTS (10) ──────────────────────────────────────────────────────────
    {
        "species_name": "Neem Tree",
        "scientific_name": "Azadirachta indica",
        "category": "plant",
        "habitat": "Tropical and subtropical dry forests, urban areas, farmland",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South Asia, Southeast Asia, Africa; widely introduced",
        "physical_description": "Fast-growing tree up to 20m. Pinnate leaves, white fragrant flowers, olive-like fruit. Evergreen in humid areas.",
        "behavior": "N/A — plant",
        "reproduction": "Seeds dispersed by birds and bats. Germinates readily.",
        "fun_facts": "Called the 'village pharmacy' in South Asia. Over 130 biologically active compounds identified. Natural insecticide.",
        "threats": "Overexploitation for medicinal use, urban development",
        "description": "Neem is one of the most important and versatile trees in Pakistan, lining streets across Lahore, Karachi, and other cities. Every part of the tree has medicinal and practical uses — leaves are used as a natural pesticide, bark for toothbrushes, seeds for neem oil used in cosmetics and agriculture, and the wood for furniture. Neem has powerful antibacterial, antifungal, and insecticidal properties, making it invaluable in organic farming. It provides dense shade in summer and is one of the few trees that can survive Pakistan's intense heat and drought.",
    },
    {
        "species_name": "Peepal Tree",
        "scientific_name": "Ficus religiosa",
        "category": "plant",
        "habitat": "Tropical and subtropical forest, urban areas, near temples and shrines",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent, Southeast Asia",
        "physical_description": "Large deciduous tree up to 30m. Heart-shaped leaves with distinctive long drip-tip. Smooth grey bark. Aerial roots.",
        "behavior": "N/A — plant",
        "reproduction": "Fig fruits eaten by birds and bats which disperse seeds.",
        "fun_facts": "One of the few trees that releases oxygen at night. Buddha attained enlightenment under a Peepal tree. Can live over 3000 years.",
        "threats": "Urban development, considered invasive in some areas as roots damage structures",
        "description": "Peepal is a sacred fig tree of immense cultural and ecological significance in South Asia. It is revered in Hindu, Buddhist, and Jain traditions — the Buddha is said to have attained enlightenment under a Peepal tree. In Pakistan, ancient Peepal trees are found near old mosques, shrines, and in historic neighbourhoods of Islamabad and Lahore. Ecologically, it is a keystone species — its figs provide food for hundreds of bird and bat species. Uniquely among trees, it releases oxygen at night through a special metabolic process.",
    },
    {
        "species_name": "Acacia",
        "scientific_name": "Acacia nilotica",
        "category": "plant",
        "habitat": "Dry savanna, riverbanks, semi-arid areas, floodplains",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Africa, Middle East, South Asia",
        "physical_description": "Medium thorny tree up to 20m. Bipinnate leaves, yellow ball-shaped flowers, long seed pods. Sharp paired thorns.",
        "behavior": "N/A — plant",
        "reproduction": "Seeds in pods dispersed by animals and water.",
        "fun_facts": "Gum arabic comes from Acacia species. Used in traditional medicine for over 3500 years.",
        "threats": "Overgrazing, charcoal production, invasive in some regions",
        "description": "Acacia (Kikar) is one of the most common trees in Pakistan's lowland areas, found along riverbanks, in dry scrubland, and in agricultural areas throughout Punjab and Sindh. It is a nitrogen-fixing tree that improves soil fertility and provides critical habitat for birds and insects. The tree produces gum arabic, used in food and pharmaceutical industries. Its wood is used for fuel and charcoal. Despite being native to Africa, it has been naturalised in Pakistan for centuries and is considered an important part of the local ecosystem.",
    },
    {
        "species_name": "Shisham Tree",
        "scientific_name": "Dalbergia sissoo",
        "category": "plant",
        "habitat": "Riverbanks, moist alluvial soil, planted in urban areas",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent, Iran",
        "physical_description": "Large deciduous tree up to 25m. Compound leaves, small white-pink flowers, flat seed pods. Deeply furrowed grey bark.",
        "behavior": "N/A — plant",
        "reproduction": "Wind-dispersed seeds in flat papery pods.",
        "fun_facts": "National tree of Pakistan. One of the most valuable timber trees in South Asia. Wood used for fine furniture.",
        "threats": "Shisham dieback disease (fungal), overexploitation for timber, urban development",
        "description": "Shisham (Dalbergia sissoo) is the national tree of Pakistan and one of the most important timber trees in South Asia. It lines roads and canals throughout Punjab and is planted extensively in urban areas for shade. Its dense, durable wood is prized for furniture, musical instruments, and construction. Shisham is a nitrogen-fixing tree that improves soil health. However, a devastating fungal disease called Shisham dieback has killed millions of trees across Pakistan since the 1990s, threatening this iconic species.",
    },
    {
        "species_name": "Chinar Tree",
        "scientific_name": "Platanus orientalis",
        "category": "plant",
        "habitat": "Riverbanks, moist valleys, urban parks, 1000-2500m elevation",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Southeast Europe, Middle East, South Asia",
        "physical_description": "Massive deciduous tree up to 30m. Large maple-like leaves turning brilliant orange-red in autumn. Distinctive mottled bark.",
        "behavior": "N/A — plant",
        "reproduction": "Wind-dispersed seeds in round hanging clusters.",
        "fun_facts": "Can live over 2000 years. Symbol of Kashmir. Alexander the Great camped under Chinar trees.",
        "threats": "Urban development, climate change affecting autumn colour timing",
        "description": "Chinar is one of the most magnificent trees in Pakistan, found in the mountain valleys of AJK, Gilgit-Baltistan, and KPK. Its spectacular autumn foliage — turning brilliant shades of orange, red, and gold — makes it one of the most beautiful trees in South Asia. Ancient Chinar trees, some over 500 years old, are found in the valleys of AJK. The tree is deeply embedded in the culture of the region and is a symbol of the Kashmir valley. It provides critical habitat for birds and insects in mountain ecosystems.",
    },
    {
        "species_name": "Wild Olive",
        "scientific_name": "Olea ferruginea",
        "category": "plant",
        "habitat": "Dry rocky hillsides, scrub forest, 500-2500m elevation",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Pakistan, Afghanistan, India, Middle East",
        "physical_description": "Small to medium evergreen tree, 5-15m. Narrow grey-green leaves, small white flowers, small olive-like fruit.",
        "behavior": "N/A — plant",
        "reproduction": "Fleshy fruits eaten by birds which disperse seeds.",
        "fun_facts": "Ancestor of cultivated olive. Extremely drought-resistant. Wood used for carving and fuel.",
        "threats": "Overgrazing preventing regeneration, collection for firewood, habitat degradation",
        "description": "Wild Olive (Kahu) is a native tree of Pakistan's dry rocky hillsides, found throughout the Salt Range, Sulaiman Range, and foothills of KPK and Balochistan. It is the wild ancestor of the cultivated olive and is extremely drought-resistant, able to survive in areas with very low rainfall. The tree provides critical food for birds through its small olive-like fruits and is an important component of Pakistan's dry scrub forest ecosystem. It is threatened by overgrazing that prevents seedling regeneration and collection for firewood.",
    },
    {
        "species_name": "Himalayan Cedar",
        "scientific_name": "Cedrus deodara",
        "category": "plant",
        "habitat": "Mountain forest, 1500-3200m elevation",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Western Himalayas — Pakistan, Afghanistan, India",
        "physical_description": "Large conifer up to 50m. Drooping branches, barrel-shaped cones, blue-green needles in clusters.",
        "behavior": "N/A — plant",
        "reproduction": "Wind-pollinated. Cones take 2 years to mature.",
        "fun_facts": "National tree of Pakistan (along with Shisham). Sacred tree in Hinduism. Wood is naturally insect-repellent.",
        "threats": "Deforestation for timber and firewood, climate change shifting habitat upward",
        "description": "Himalayan Cedar (Deodar) is one of Pakistan's most majestic trees, forming dense forests in the mountain valleys of KPK, AJK, and Gilgit-Baltistan between 1,500 and 3,200m elevation. It is one of Pakistan's national trees and is sacred in Hindu tradition. The Deodar forests of Swat, Kaghan, and Chitral are among the most beautiful in the world. The wood is naturally insect-repellent and highly durable, making it prized for construction and furniture. These forests are critically important for watershed protection and biodiversity.",
    },
    {
        "species_name": "Mango Tree",
        "scientific_name": "Mangifera indica",
        "category": "plant",
        "habitat": "Tropical and subtropical areas, orchards, urban gardens",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia; cultivated worldwide",
        "physical_description": "Large evergreen tree up to 40m. Long lance-shaped leaves, small fragrant flowers, large fleshy fruit.",
        "behavior": "N/A — plant",
        "reproduction": "Large fleshy fruits eaten by animals and humans which disperse seeds.",
        "fun_facts": "National fruit of Pakistan, India, and Philippines. Over 1000 varieties exist. Cultivated for over 4000 years.",
        "threats": "Climate change affecting flowering and fruiting, fungal diseases, water scarcity",
        "description": "Mango is Pakistan's national fruit and one of the most economically important trees in the country. Pakistan is one of the world's top mango producers, with the Chaunsa, Sindhri, and Anwar Ratol varieties being internationally renowned. Mango orchards cover vast areas of Punjab and Sindh, providing livelihoods for millions of farmers. The tree also provides critical habitat for birds, bats, and insects. Climate change is increasingly affecting mango production by disrupting the cool winter temperatures needed to trigger flowering.",
    },
    {
        "species_name": "Banyan Tree",
        "scientific_name": "Ficus benghalensis",
        "category": "plant",
        "habitat": "Tropical forest, urban areas, near temples and shrines",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Indian subcontinent, Southeast Asia",
        "physical_description": "Massive tree spreading via aerial roots that become secondary trunks. Can cover several acres. Oval leathery leaves.",
        "behavior": "N/A — plant",
        "reproduction": "Fig fruits eaten by birds and bats which disperse seeds.",
        "fun_facts": "National tree of India. A single tree in Kolkata covers 1.5 hectares. Sacred in Hinduism.",
        "threats": "Urban development, considered invasive as roots damage structures",
        "description": "Banyan is one of the most ecologically important trees in Pakistan, found near old shrines, mosques, and in historic areas of Sindh and Punjab. It is a keystone species — its figs provide food for over 60 species of birds and mammals. The Banyan spreads by sending down aerial roots that become secondary trunks, allowing a single tree to cover a vast area. Ancient Banyan trees are considered sacred in South Asian traditions and are often the centre of village life, providing shade for community gatherings.",
    },
    {
        "species_name": "Bamboo",
        "scientific_name": "Bambusa bambos",
        "category": "plant",
        "habitat": "Riverbanks, moist forest, tropical and subtropical areas",
        "diet": "N/A — photosynthetic",
        "predators": "N/A",
        "prey": "N/A",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Giant grass up to 30m. Hollow woody culms (stems), lance-shaped leaves, thorny branches.",
        "behavior": "N/A — plant",
        "reproduction": "Spreads via underground rhizomes. Flowers rarely — once every 40-120 years — then dies.",
        "fun_facts": "Fastest growing plant on Earth — can grow 91cm per day. Stronger than steel by weight.",
        "threats": "Overexploitation for construction and crafts, habitat loss",
        "description": "Bamboo is found along riverbanks and in moist forest areas of KPK, AJK, and parts of Punjab in Pakistan. It is the fastest growing plant on Earth and one of the most versatile — used for construction, furniture, paper, food, and crafts. Bamboo groves provide critical habitat for birds and small mammals. It is a highly sustainable resource as it regrows rapidly after harvesting without replanting. Bamboo's extensive root system prevents soil erosion along riverbanks, making it important for watershed protection.",
    },
    # ── INSECTS (7) ──────────────────────────────────────────────────────────
    {
        "species_name": "Common Jezebel Butterfly",
        "scientific_name": "Delias eucharis",
        "category": "insect",
        "habitat": "Forest edges, gardens, open woodland, parks — common across Pakistan",
        "diet": "Larvae: mistletoe plants. Adults: nectar from flowers.",
        "predators": "Birds, spiders, wasps",
        "prey": "Mistletoe plants (larvae)",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia — very common in Pakistan, India, Sri Lanka",
        "physical_description": "Medium butterfly, 6-7cm wingspan. White upperside with black borders. Brilliant yellow, red, and orange underside — one of the most colourful butterflies in Pakistan.",
        "behavior": "Flies high in tree canopy. Males congregate on hilltops. Females lay eggs on mistletoe.",
        "reproduction": "Eggs laid in clusters on mistletoe. Caterpillars feed gregariously.",
        "fun_facts": "One of the most common and recognisable butterflies in Pakistan. The brilliant underside colours warn predators of toxicity from mistletoe compounds.",
        "threats": "Habitat loss, pesticide use, loss of mistletoe host plants",
        "description": "Common Jezebel Butterfly is one of the most beautiful and commonly seen butterflies in Pakistan, found in gardens, parks, and forest edges across the country from Karachi to Islamabad. Its brilliant yellow, red, and orange underside makes it unmistakable when it opens its wings. The caterpillars feed on mistletoe plants, acquiring toxic compounds that make the adult butterfly unpalatable to predators. Unlike the Monarch Butterfly which is primarily an American species, the Common Jezebel is genuinely native to and abundant in Pakistan, making it a true representative of Pakistan's butterfly fauna.",
    },
    {
        "species_name": "Atlas Moth",
        "scientific_name": "Attacus atlas",
        "category": "insect",
        "habitat": "Tropical and subtropical forest, forested hills",
        "diet": "Larvae: leaves of various trees. Adults: no functional mouth — do not eat.",
        "predators": "Birds, bats, spiders",
        "prey": "Tree leaves (larvae only)",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "One of the largest moths in the world. Wingspan up to 25-30cm. Rich brown wings with triangular transparent patches and snake-head wing tips.",
        "behavior": "Adults live only 1-2 weeks, surviving on fat reserves. Attracted to light. Females release pheromones to attract males.",
        "reproduction": "Eggs laid on host plant leaves. Caterpillar pupates in silk cocoon.",
        "fun_facts": "Wing tips resemble snake heads — a predator deterrent. Silk from cocoons used for small purses in Taiwan.",
        "threats": "Deforestation, light pollution disrupting mating, collection",
        "description": "Atlas Moth is one of the largest and most spectacular moths in the world, with a wingspan that can reach 30cm. It is found in the forested hills of KPK and AJK in Pakistan. The adult moth has no functional mouth and cannot eat — it survives entirely on fat reserves accumulated during the caterpillar stage, living for only 1-2 weeks. Its wing tips have evolved to resemble snake heads, deterring predators. The Atlas Moth is threatened by deforestation that destroys its larval host plants and light pollution that disrupts its mating behaviour.",
    },
    {
        "species_name": "Common Tiger Butterfly",
        "scientific_name": "Danaus genutia",
        "category": "insect",
        "habitat": "Gardens, open woodland, scrubland, urban parks",
        "diet": "Larvae: milkweed and related plants. Adults: flower nectar.",
        "predators": "Birds (avoided due to toxicity), spiders",
        "prey": "Milkweed plants (larvae)",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia, Australia",
        "physical_description": "Medium butterfly, 7-8cm wingspan. Orange wings with black veins and white spots on black border. Similar to Monarch.",
        "behavior": "Slow, gliding flight. Toxic to predators. Migrates seasonally in some areas.",
        "reproduction": "Eggs laid singly on milkweed leaves. Complete metamorphosis.",
        "fun_facts": "Closely related to Monarch Butterfly. Uses same chemical defence from milkweed. Important pollinator.",
        "threats": "Pesticide use, habitat loss, milkweed reduction",
        "description": "Common Tiger Butterfly is one of the most widespread and familiar butterflies in Pakistan, found in gardens, parks, and open areas across the country. Its bright orange and black pattern is a warning to predators of its toxicity, acquired from milkweed plants consumed as a caterpillar. It is an important pollinator, visiting a wide range of flowering plants. Like its close relative the Monarch, it is threatened by the widespread use of pesticides that kill both the butterfly and its milkweed host plants.",
    },
    {
        "species_name": "Asian Honeybee",
        "scientific_name": "Apis cerana indica",
        "category": "insect",
        "habitat": "Forest, farmland, gardens, urban areas — wherever flowers are present",
        "diet": "Nectar and pollen from flowers — essential pollinator for agriculture and crops",
        "predators": "Birds (bee-eaters), spiders, wasps, hornets, bears",
        "prey": "None — herbivore/nectarivore",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Small bee, 10-11mm. Yellow and black banded abdomen. Smaller than European honeybee.",
        "behavior": "Highly social, colonies of 6,000-7,000. Performs waggle dance to communicate food location. Resistant to Varroa mite.",
        "reproduction": "Queen lays up to 1000 eggs per day. Workers live 6 weeks in summer.",
        "fun_facts": "Pollinates 70% of crop species in South Asia. Resistant to Varroa mite that devastates European bees. Produces high-quality honey.",
        "threats": "Pesticide use, habitat loss, disease, competition from introduced European honeybee",
        "description": "Asian Honeybee is the native honeybee of Pakistan and one of the most ecologically and economically important beneficial insects for agriculture in the country. It is a vital agricultural pollinator — pollinates the majority of Pakistan's food crops including mangoes, citrus, cotton, and vegetables — without it, agricultural production and farming would collapse. This beneficial insect provides essential pollination services and agricultural pest control through crop pollination. Unlike the introduced European honeybee, the Asian Honeybee has natural resistance to the Varroa mite, a devastating parasite. It is threatened by the widespread use of pesticides in agriculture, which kills bees directly and reduces the availability of flowering plants. Honey production from this species supports rural livelihoods across Pakistan.",
    },
    {
        "species_name": "Praying Mantis",
        "scientific_name": "Hierodula membranacea",
        "category": "insect",
        "habitat": "Gardens, scrubland, forest edges, grassland",
        "diet": "Insects, spiders, small lizards, frogs, hummingbirds",
        "predators": "Birds, bats, spiders, larger mantises",
        "prey": "Insects, spiders, small vertebrates",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia",
        "physical_description": "Large mantis, 6-9cm. Bright green or brown. Triangular head with large compound eyes, raptorial forelegs.",
        "behavior": "Ambush predator. Camouflages perfectly in vegetation. Female sometimes eats male after mating.",
        "reproduction": "Female lays 100-400 eggs in foam egg case (ootheca) attached to plant.",
        "fun_facts": "Only insect that can turn its head 180 degrees. Can catch and eat hummingbirds. Used in biological pest control.",
        "threats": "Pesticide use, habitat loss",
        "description": "Praying Mantis is a fascinating and beneficial insect found throughout Pakistan's gardens, scrubland, and agricultural areas. It is an apex insect predator, consuming large numbers of pest insects including aphids, caterpillars, and beetles, making it a valuable natural pest control agent. The Praying Mantis is a master of camouflage, perfectly matching the colour and texture of leaves and stems. It is the only insect capable of turning its head 180 degrees, giving it exceptional visual awareness of its surroundings.",
    },
    {
        "species_name": "Giant Wood Spider",
        "scientific_name": "Nephila pilipes",
        "category": "insect",
        "habitat": "Forest edges, gardens, scrubland",
        "diet": "Flying insects — moths, beetles, flies, small birds occasionally",
        "predators": "Birds, wasps, larger spiders",
        "prey": "Flying insects, occasionally small birds",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "South and Southeast Asia, Australia",
        "physical_description": "Large orb-weaving spider. Female up to 5cm body, 15cm leg span. Yellow and black abdomen. Male tiny (6mm).",
        "behavior": "Builds large golden orb webs up to 1.5m diameter. Web silk is the strongest natural fibre known.",
        "reproduction": "Female lays 300-3000 eggs in silk sac. Male much smaller than female.",
        "fun_facts": "Web silk is stronger than steel by weight. Web has golden colour visible in sunlight. Can occasionally catch small birds.",
        "threats": "Habitat loss, pesticide use reducing prey",
        "description": "Giant Wood Spider is one of the largest spiders in Pakistan, found in the forests and gardens of KPK, AJK, and parts of Punjab. The female builds enormous golden orb webs up to 1.5m in diameter that are strong enough to occasionally trap small birds. The silk of this spider is the strongest natural fibre known — stronger than steel by weight — and has been studied for potential applications in medicine and materials science. Despite its intimidating size, it is harmless to humans and is a highly beneficial predator of pest insects.",
    },
    {
        "species_name": "Desert Locust",
        "scientific_name": "Schistocerca gregaria",
        "category": "insect",
        "habitat": "Arid and semi-arid areas, desert, dry grassland",
        "diet": "All green vegetation — crops, grasses, leaves",
        "predators": "Birds, lizards, spiders, humans",
        "prey": "None — herbivore",
        "conservation_status": "LC",
        "found_in_pakistan": True,
        "geographical_range": "Africa, Middle East, South Asia",
        "physical_description": "Medium insect, 4.5-6cm. Yellow (adult) or brown/black (juvenile). Large hind legs for jumping. Wings for long-distance flight.",
        "behavior": "Solitary phase and gregarious (swarming) phase. Swarms of billions can travel 150km per day.",
        "reproduction": "Female lays 80-160 eggs in soil pods. Multiple generations per year.",
        "fun_facts": "A swarm of 1 billion locusts can eat the same amount of food as 35,000 people in one day. 2020 swarms were worst in 70 years.",
        "threats": "Considered a pest — controlled with pesticides. Climate change increasing outbreak frequency.",
        "description": "Desert Locust is one of the most destructive insects in the world and a major threat to food security in Pakistan. Under normal conditions, locusts are solitary and harmless. But when population density increases, they transform into a gregarious swarming phase, forming swarms of billions that can devastate entire harvests in hours. Pakistan experienced severe locust invasions in 2020, the worst in 70 years, destroying crops across Sindh, Punjab, and Balochistan. Climate change is increasing the frequency and severity of locust outbreaks by creating more favourable breeding conditions.",
    },
]
